version: '3'
services:
  traefik:
    image: "traefik:v2.0.0-rc3"
    container_name: "traefik"
    command:
    #- "--log.level=DEBUG"
    - "--api.insecure=true"
    - "--providers.docker=true"
    - "--providers.docker.exposedbydefault=false"
    - "--entrypoints.web.address=:80"
    - "--entrypoints.websecure.address=:443"
    - "--certificatesresolvers.myhttpchallenge.acme.httpchallenge=true"
    - "--certificatesresolvers.myhttpchallenge.acme.httpchallenge.entrypoint=web"
    #- "--certificatesresolvers.myhttpchallenge.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
    - "--certificatesresolvers.myhttpchallenge.acme.email=edouard.touraille@gmail.com"
    - "--certificatesresolvers.myhttpchallenge.acme.storage=/letsencrypt/acme.json"
    ports:
    - "80:80"
    - "443:443"
    - "8080:8080"
    volumes:
    - "./letsencrypt:/letsencrypt"
    - "/var/run/docker.sock:/var/run/docker.sock:ro"

  php:
      build: php
      volumes:
          - ./../.:/src
      links:
       - db
      #network_mode: host
      environment:
        - WEB_DOCUMENT_ROOT=/src/public
      ports:
        - "80:80"
      labels:
      - "traefik.enable=true"
      - "traefik.http.routers.php.rule=Host(`stockx.sneakers-heat.com`)"
      - "traefik.http.routers.php.entrypoints=websecure"
      - "traefik.http.routers.php.tls.certresolver=myhttpchallenge"

  db:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=failleDeSecuritet
      - MYSQL_DATABASE=symfony
      - MYSQL_USER=ed
      - MYSQL_PASSWORD=b1otope
      - TERM=dumb
    volumes:
      - ./db:/etc/mysql/conf.d
      - ./:/opt
    tty: true

  phpmyadmin:
     image: corbinu/docker-phpmyadmin
     restart: always
     ports :
      - "85:80"
     environment:
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=failleDeSecuritet
      - MYSQL_PORT_3306_TCP_ADDR=db
     links:
      - db:mysql
     #labels:
     #- "traefik.enable=true"
     #- "traefik.http.routers.php.rule=Host(`stockx.sneakers-heat.com`)"
     #- "traefik.http.routers.php.entrypoints=websecure"
     #- "traefik.http.routers.php.tls.certresolver=myhttpchallenge"

