version: '3'
services:
 php:
      build: php
      volumes:
          - ./../.:/src
      links:
       - db
      #network_mode: host
      environment:
        - WEB_DOCUMENT_ROOT=/src/public
      ports:
        - "81:80"
      container_name: "php"
      labels:
       - "traefik.backend=back"
       - "traefik.frontend.rule=Host:stockx.sneakers-heat.com"
       - "traefik.enable=true"
       - "traefik.port=80"
       - "traefik.docker.network=web"
      networks:
       - "web"
       - "default"
 db:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=failleDeSecuritet
      - MYSQL_DATABASE=symfony
      - MYSQL_USER=ed
      - MYSQL_PASSWORD=b1otope
      - TERM=dumb
    volumes:
      - ./db:/etc/mysql/conf.d
      - ./:/opt
    tty: true

 phpmyadmin:
     image: corbinu/docker-phpmyadmin
     restart: always
     ports :
      - "85:80"
     environment:
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=failleDeSecuritet
      - MYSQL_PORT_3306_TCP_ADDR=db
     links:
      - db:mysql
     labels:
      - "traefik.backend=db"
      - "traefik.frontend.rule=Host:db.sneakers-heat.com"
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.docker.network=web"
     networks:
      - "web"
      - "default"

 logstash:
   image: docker.elastic.co/logstash/logstash:7.4.2
   volumes:
   - ./pipeline/:/usr/share/logstash/pipeline/
   ports:
   - "12201:12201"

 elasticsearch:
     image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
     ports:
     - "9200:9200"
     environment:
     - discovery.type=single-node


 kibana:
     image:  docker.elastic.co/kibana/kibana:7.4.2
     links:
     - elasticsearch
     ports:
     - "5601:5601"
     labels:
     - "traefik.backend=kibana"
     - "traefik.frontend.rule=Host:kibana.sneakers-heat.com"
     - "traefik.enable=true"
     - "traefik.port=5601"
     - "traefik.docker.network=web"
     networks:
     - "web"
     - "default"



networks:
  web:
    external:
      name: web
